// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY3oPtGSsaMGYai9JqebykWNKbLIIpUWA',
    appId: '1:515028757334:web:0a8b255006ab99f8ae04f7',
    messagingSenderId: '515028757334',
    projectId: 'reuse-app-project',
    authDomain: 'reuse-app-project.firebaseapp.com',
    storageBucket: 'reuse-app-project.firebasestorage.app',
    measurementId: 'G-HLV5ZXBFCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqpfx7yvz8_CkojvJuwHrHDQfRPPYsVdM',
    appId: '1:515028757334:android:ebf2150fa6da84d0ae04f7',
    messagingSenderId: '515028757334',
    projectId: 'reuse-app-project',
    storageBucket: 'reuse-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewFRJsO8DMgeF5EXuMTOsx9lrfEv8W48',
    appId: '1:515028757334:ios:12adf64d73124428ae04f7',
    messagingSenderId: '515028757334',
    projectId: 'reuse-app-project',
    storageBucket: 'reuse-app-project.firebasestorage.app',
    iosBundleId: 'com.example.reuse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewFRJsO8DMgeF5EXuMTOsx9lrfEv8W48',
    appId: '1:515028757334:ios:12adf64d73124428ae04f7',
    messagingSenderId: '515028757334',
    projectId: 'reuse-app-project',
    storageBucket: 'reuse-app-project.firebasestorage.app',
    iosBundleId: 'com.example.reuse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY3oPtGSsaMGYai9JqebykWNKbLIIpUWA',
    appId: '1:515028757334:web:cedaae731c5888f5ae04f7',
    messagingSenderId: '515028757334',
    projectId: 'reuse-app-project',
    authDomain: 'reuse-app-project.firebaseapp.com',
    storageBucket: 'reuse-app-project.firebasestorage.app',
    measurementId: 'G-YVLYFCQHB7',
  );
}
